spring:
  config:
    import: secretkey.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      maxFileSize: 50MB # 파일 하나의 최대 크기
      maxRequestSize: 50MB  # 한 번에 최대 업로드 가능 용량



cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD
  allowed-headers: '*'
  max-age: 3600

logging:
  level:
    org.hibernate.SQL: debug