spring:
  config:
    import: db.yml, secretkey.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      maxFileSize: 50MB # 파일 하나의 최대 크기
      maxRequestSize: 50MB  # 한 번에 최대 업로드 가능 용량

logging:
  level:
    org.hibernate.SQL: debug

