# DB Source URL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chukchuk_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
